name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}